language: java
jdk: oraclejdk8
dist: trusty
addons:
  artifacts:
    debug: true
    paths: $(ls target/spinnaker-demo*.jar)
    target_paths:
    - /${TRAVIS_REPO_SLUG}
after_script: curl -k -X POST https://api.spinnaker.demo.sanpablo.cf-app.com/webhooks/webhook/rickandmorty
