spring:
  application.name: rickandmorty
  resources:
    chain.cache: false
    cache.period: 0
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'    
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: false
  metrics:
    export:
      datadog:
        api-key: ${DATADOG_API_KEY}
        application-key: ${DATADOG_APPLICATION_KEY}
        host-tag: ${spring.application.name}
        step: 10s
        enabled: true
    web:
      server:
        auto-time-requests: true
